export const BOOTCAMPS_SET_DATA = "BOOTCAMPS_SET_DATA";
export const BOOTCAMP_GET_SINGLE = "BOOTCAMP_GET_SINGLE";
export const BOOTCAMPS_SET_REVIEWS_DATA = "BOOTCAMPS_SET_REVIEWS_DATA";
export const GET_COURSES_FOR_SINGLE_BOOTCAMP = "GET_COURSES_FOR_SINGLE_BOOTCAMP";
export const GET_REVIEWS_FOR_SINGLE_BOOTCAMP = "GET_REVIEWS_FOR_SINGLE_BOOTCAMP";
export const CLEAR_SINGLE_BOOTCAMP = "CLEAR_SINGLE_BOOTCAMP";
export const BOOTCAMPS_SET_FILTER = "BOOTCAMPS_SET_FILTER";
export const BOOTCAMPS_CLEAR_FILTER = "BOOTCAMPS_CLEAR_FILTER";
